[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=ExtractOnly
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=I
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=C:\Users\User\Dropbox\fichiers pour aider des programmes\user licence.txt
FinishMessage=
TargetName=C:\Users\User\Dropbox\fichiers pour aider des programmes\différentes techniques pour installer un programme informatique.exe
FriendlyName=différentes techniques pour installer un programme informatique.exe
AppLaunched=
PostInstallCmd=
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="differentes_techniques_pour_installer_un_programme_informatique.bat"
[SourceFiles]
SourceFiles0=C:\Users\User\Dropbox\fichiers pour aider des programmes\programme\
[SourceFiles0]
%FILE0%=
